<?php

declare(strict_types=1);

namespace Shakil\Fast2sms\Console\Commands;

use Illuminate\Console\Command;

/**
 * Generates an IDE helper stub file documenting all Fast2sms facade methods.
 */
class GenerateIdeHelper extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'fast2sms:ide-helper
                          {--path= : The path where the IDE helper file will be generated (default: project root)}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate an IDE helper stub file for Fast2sms facade autocompletion';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $path = $this->option('path') ?? base_path('_ide_helper_fast2sms.php');

        $stub = $this->buildStub();

        file_put_contents($path, $stub);

        $this->components->info("IDE helper generated at: {$path}");

        return self::SUCCESS;
    }

    private function buildStub(): string
    {
        return <<<'PHP'
<?php

// @formatter:off
// phpcs:ignoreFile
/**
 * Fast2sms IDE Helper
 *
 * This file is auto-generated by `php artisan fast2sms:ide-helper`.
 * Do NOT edit this file manually — re-run the command to regenerate.
 *
 * @see \Shakil\Fast2sms\Fast2sms
 */

namespace Shakil\Fast2sms\Facades {

    use Closure;
    use DateTimeInterface;
    use Illuminate\Support\Collection;
    use Shakil\Fast2sms\Contracts\WhatsAppInterface;
    use Shakil\Fast2sms\DataTransferObjects\SmsParameters;
    use Shakil\Fast2sms\DataTransferObjects\WhatsAppParameters;
    use Shakil\Fast2sms\Enums\SmsLanguage;
    use Shakil\Fast2sms\Enums\SmsRoute;
    use Shakil\Fast2sms\Enums\WhatsAppType;
    use Shakil\Fast2sms\Exceptions\Fast2smsException;
    use Shakil\Fast2sms\Responses\Fast2smsResponse;
    use Shakil\Fast2sms\Responses\WalletBalanceResponse;
    use Shakil\Fast2sms\Testing\Fast2smsFake;
    use Shakil\Fast2sms\Testing\RecordedSmsSend;
    use Shakil\Fast2sms\Testing\RecordedWhatsAppSend;

    /**
     * @see \Shakil\Fast2sms\Fast2sms
     */
    class Fast2sms
    {
        /** Set the recipient number(s). */
        public static function to(string|array $numbers): \Shakil\Fast2sms\Fast2sms {}

        /** Set the message content. */
        public static function message(string $message): \Shakil\Fast2sms\Fast2sms {}

        /** Set the sender ID. */
        public static function senderId(string $senderId): \Shakil\Fast2sms\Fast2sms {}

        /** Set the SMS route. */
        public static function route(SmsRoute $route): \Shakil\Fast2sms\Fast2sms {}

        /** Set the DLT entity ID. */
        public static function entityId(string $entityId): \Shakil\Fast2sms\Fast2sms {}

        /** Set the DLT template ID. */
        public static function templateId(string $templateId): \Shakil\Fast2sms\Fast2sms {}

        /** Set template variable values. */
        public static function variables(array $values): \Shakil\Fast2sms\Fast2sms {}

        /** Enable flash SMS. */
        public static function flash(bool $flash = true): \Shakil\Fast2sms\Fast2sms {}

        /** Schedule the SMS for a future time. */
        public static function schedule(string|DateTimeInterface $time): \Shakil\Fast2sms\Fast2sms {}

        /** Set the message language. */
        public static function language(SmsLanguage $language): \Shakil\Fast2sms\Fast2sms {}

        /** Send the SMS. */
        public static function send(): Fast2smsResponse {}

        /** Send a quick SMS. */
        public static function quick(string|array $numbers, string $message, ?SmsLanguage $language = null): Fast2smsResponse {}

        /** Send a DLT SMS. */
        public static function dlt(string|array $numbers, string $templateId, array|string $variablesValues, ?string $senderId = null, ?string $entityId = null): Fast2smsResponse {}

        /** Send an OTP SMS. */
        public static function otp(string|array $numbers, string $otpValue): Fast2smsResponse {}

        /** Check wallet balance. */
        public static function checkBalance(): WalletBalanceResponse {}

        /** Get DLT manager details. */
        public static function dltManager(string $type): Fast2smsResponse {}

        /** Get the WhatsApp service instance. */
        public static function whatsapp(): WhatsAppInterface {}

        /** Get the WhatsApp service instance with a recipient pre-set. */
        public static function viaWhatsApp(string|array|null $to = null): WhatsAppInterface {}

        /** Enable queued sending. */
        public static function queue(): void {}

        /** Set the queue connection for the next send. */
        public static function onConnection(string $connection): \Shakil\Fast2sms\Fast2sms {}

        /** Set the queue name for the next send. */
        public static function onQueue(string $queue): \Shakil\Fast2sms\Fast2sms {}

        /** Set the queue delay in seconds. */
        public static function delay(int $seconds): \Shakil\Fast2sms\Fast2sms {}

        /** Enable faking for tests. */
        public static function fake(): Fast2smsFake {}

        /** Return a map of all package events to their descriptions. */
        public static function events(): array {}

        public static function assertSent(array|Closure|null $callback = null): void {}
        public static function assertNotSent(array|Closure|null $callback = null): void {}
        public static function assertSentTimes(int $count): void {}
        public static function assertSmsSent(?Closure $callback = null): void {}
        public static function assertSmsNotSent(?Closure $callback = null): void {}
        public static function assertSmsSentCount(int $count): void {}
        public static function assertSmsSentTo(string $number): void {}
        public static function assertSmsSentWithMessage(string $message): void {}
        public static function assertSmsSentWithRoute(SmsRoute $route): void {}
        public static function assertWhatsAppSent(?Closure $callback = null): void {}
        public static function assertWhatsAppNotSent(?Closure $callback = null): void {}
        public static function assertWhatsAppSentCount(int $count): void {}
        public static function assertWhatsAppSentTo(string $number): void {}
        public static function assertWhatsAppSentWithType(WhatsAppType $type): void {}
        public static function assertNothingSent(): void {}
        public static function assertSentCount(int $expected): void {}

        /** @return Collection<int, array<string, mixed>> */
        public static function sentMessages(): Collection {}

        /** @return list<RecordedSmsSend> */
        public static function sentSms(): array {}

        /** @return list<RecordedWhatsAppSend> */
        public static function sentWhatsApp(): array {}
    }
}
PHP;
    }
}
